%global momorel 3

Name:           perl-XML-LibXML-Simple
Version:        0.13
Release:        %{momorel}m%{?dist}
Summary:        XML::LibXML clone of XML::Simple::XMLin()
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-LibXML-Simple/
Source0:        http://www.cpan.org/authors/id/M/MA/MARKOV/XML-LibXML-Simple-%{version}.tar.gz
NoSource:       0
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
#BuildRequires:  perl-ExtUtils-MakeMaker
BuildRequires:  perl-File-Slurp
#BuildRequires:  perl-Test-Simple
BuildRequires:  perl-Test-Pod >= 1.00
BuildRequires:  perl-XML-LibXML >= 1.58
Requires:       perl(File::Slurp)
Requires:       perl(Test::More) >= 0.54
Requires:       perl(Test::Pod) >= 1.00
Requires:       perl(XML::LibXML) >= 1.58
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is a blunt rewrite of XML::Simple (by Grant McLean) to use the
XML::LibXML parser for XML structures, where the original uses plain Perl
or SAX parsers.

%prep
%setup -q -n XML-LibXML-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

chmod -R u+rwX,go+rX,go-w %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc ChangeLog README
%{perl_vendorlib}/XML/LibXML/Simple*
%{_mandir}/man3/*

%changelog
* Tue Jun  2 2009 NAKAYA Toshiharu <nakaya@momonga-linux.org>
- (0.13-3m)
- remove duplicate directories

* Mon Jun 01 2009 NAKAYA Toshiharu <nakaya@momonga-linux.org>
- (0.13-2m)
- modify BuildRequires

* Sat May 30 2009 Nakamura Hirotaka<h_nakamura@momonga-linux.org>
- (0.13-1m)
- Specfile autogenerated by cpanspec 1.78 for Momonga Linux.
