#! /bin/sh

# This is a startup/shutdown script for the ZOOM-Perl test-server,
# suitable for use in a SysV-style init directory such as /etc/init.d
# (on Debian systems) and /etc/rc.d/init.d (on Red Hat systems).  This
# is configured to run on z3950.indexdata.com -- if you want to run it
# somewhere else, you'll probably need to tweak it to suit your
# system's paths.

### BEGIN INIT INFO
# Provides:   zoom-perl-server
# Required-Start: $local_fs $remote_fs $network $syslog $named
# Required-Stop:  $local_fs $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    ZOOM-Perl test server
# Description:    Controls the ZOOM-Perl test server
### END INIT INFO


PATH=/bin:/usr/bin
logfile=/var/log/zoom-perl-test-server
pidfile=/var/run/zoom-perl-test-server.pid

case "$1" in
  start)
	if [ -f $pidfile ]; then
		echo "ZOOM-Perl test server seems to be already running"
		exit 1
	fi
	echo "Starting ZOOM-Perl test server"
	test -f $logfile && mv $logfile $logfile.old
	( cd /home/mike/ZOOM-Perl/archive/test-server
	  zebrasrv-2.0 -c test-server.cfg @:2100 > $logfile 2>&1 < /dev/null &
	  echo $! > $pidfile
	)
	;;
  stop)
	if [ ! -f $pidfile ]; then
		echo "ZOOM-Perl test server does not seem to be running"
		exit 1
	fi
	echo "Stopping ZOOM-Perl test server"
	kill `cat $pidfile`
	rm $pidfile
	;;
  restart)
	$0 stop && $0 start
	;;
  *)
	echo "Usage: $0 start|stop|restart" >&2
        ;;
esac
